import localFont from "next/font/local";
import "./globals.css";

const futuraLight = localFont({
  src: "../../public/Fonts/FuturaCyrillicLight.ttf",
  variable: "--font-futura-light",
});

const futuraMedium = localFont({
  src: "../../public/Fonts/FuturaCyrillicMedium.ttf",
  variable: "--font-futura-medium",
});

export const metadata = {
  title: "Ableton Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${futuraLight.variable} ${futuraMedium.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
